# docker-compose.local.yml
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: oneday-onestreak-local
    ports:
      - "8080:8080"
    env_file:
      - .env/docker.local.env
    volumes:
      - ./logs:/app/logs