# docker-compose.main.yml
services:
  app:
    image: 1d1s/oneday-onestreak:${TAG}
    container_name: oneday-onestreak-main
    ports:
      - "127.0.0.1:18080:8080"
    restart: always
    volumes:
      - /var/log/oneday:/app/logs
    env_file:
      - .env/docker.main.env
